# -*- coding: utf-8 -*-
"""LLM-Powered Document Retrieval System (RAG).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fos_6Wfhai1hO9IMAZjvYsxT1MuQWOZV
"""

# Cell 1: Clean install with correct modern packages
# Install all necessary Python libraries for the RAG system.
# - `langchain-core`: Core LangChain components.
# - `langchain-groq`: Integrates with Groq for LLM access.
# - `langchain-huggingface`: For using HuggingFace models, specifically embeddings.
# - `langchain-chroma`: Integrates with ChromaDB for vector store functionality.
# - `pypdf`: Used for loading PDF documents.
# - `sentence-transformers`: For creating embeddings using pre-trained models.
# - `langchain-text-splitters`: For splitting documents into manageable chunks.
# - `langchain-community`: Contains various community-contributed LangChain components.
# The `-q` flag stands for 'quiet', suppressing most installation output.
!pip install -q langchain-core langchain-groq langchain-huggingface langchain-chroma pypdf sentence-transformers langchain-text-splitters langchain-community

# Cell 2: Full RAG System — modern LangChain (no langchain.chains at all)
import os
from google.colab import userdata

# ✅ All modern imports — no langchain.chains dependency, using standalone packages for better modularity.
# PyPDFLoader: Used to load documents from PDF files.
from langchain_community.document_loaders import PyPDFLoader
# RecursiveCharacterTextSplitter: Breaks down documents into smaller, semantically meaningful chunks.
from langchain_text_splitters import RecursiveCharacterTextSplitter
# HuggingFaceEmbeddings: Generates vector embeddings for text using HuggingFace models.
from langchain_huggingface import HuggingFaceEmbeddings
# ChatGroq: LangChain integration for Groq's chat models.
from langchain_groq import ChatGroq
# Chroma: Standalone package for ChromaDB vector store operations.
from langchain_chroma import Chroma                          # ✅ standalone package now
# PromptTemplate: Defines the structure of the prompts sent to the LLM.
from langchain_core.prompts import PromptTemplate
# StrOutputParser: Parses the LLM's output into a simple string.
from langchain_core.output_parsers import StrOutputParser
# RunnablePassthrough: Allows input to pass through directly in an LCEL chain.
from langchain_core.runnables import RunnablePassthrough     # ✅ replaces create_retrieval_chain

# Load API key for Groq
# Retrieves the API key from Colab's user data secrets for secure access.
try:
    os.environ["GROQ_API_KEY"] = userdata.get('GROQ_API_KEY')
    print("✅ API key loaded.")
except Exception:
    raise ValueError("Add 'GROQ_API_KEY' to the Secrets (🔑) tab in Colab.")


class RAGSystem:
    """
    A class to encapsulate the Retrieval Augmented Generation (RAG) system.
    Handles document ingestion, vector store management, and querying using an LLM.
    """
    def __init__(
        self,
        file_path: str = "/content/Pratik Gaikar - ATS Data Resume.pdf",
        persist_dir: str = "/content/chroma_db"
    ):
        """
        Initializes the RAGSystem with a document path and a persistence directory for ChromaDB.
        Loads embeddings and the LLM, and attempts to load an existing vector store.
        """
        self.file_path = file_path
        self.persist_dir = persist_dir
        self.vector_store = None

        print("Loading HuggingFace embeddings (all-MiniLM-L6-v2)...")
        # Initialize HuggingFace embeddings for text conversion to vectors.
        self.embeddings = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

        print("Initializing Groq LLM (llama-3.1-8b-instant)...")
        # Initialize the Groq Chat model with a specific model name and temperature.
        self.llm = ChatGroq(model_name="llama-3.1-8b-instant", temperature=0)

        # Load existing vector store if available
        # Checks if the persistence directory exists and contains data to load the ChromaDB.
        if os.path.exists(persist_dir) and os.listdir(persist_dir):
            print("✅ Found existing vector store — loading it.")
            self.vector_store = Chroma(
                persist_directory=persist_dir,
                embedding_function=self.embeddings
            )
        else:
            print("⚠️  No vector store found. Call ingest_documents() to build one.")

    def ingest_documents(self):
        """Load PDF → chunk → embed → persist to Chroma."""
        # Ensures the PDF file exists before proceeding.
        if not os.path.exists(self.file_path):
            raise FileNotFoundError(f"PDF not found at: {self.file_path}")

        print(f"📄 Loading: {self.file_path}")
        # Load the PDF document using PyPDFLoader.
        loader = PyPDFLoader(self.file_path)
        documents = loader.load()
        print(f"   Loaded {len(documents)} page(s).")

        # Split the loaded documents into smaller chunks for effective retrieval.
        # `chunk_size`: Maximum size of each text chunk.
        # `chunk_overlap`: Overlap between consecutive chunks to maintain context.
        splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
        chunks = splitter.split_documents(documents)
        print(f"   Split into {len(chunks)} chunks.")

        print("🔢 Embedding and storing in Chroma...")
        # Create a new Chroma vector store from the document chunks and embeddings.
        # The vector store is persisted to the specified directory.
        self.vector_store = Chroma.from_documents(
            documents=chunks,
            embedding=self.embeddings,
            persist_directory=self.persist_dir
        )
        print("✅ Ingestion complete.")

    def query(self, question: str) -> str:
        """Run a question through the RAG pipeline using LCEL (modern approach)."""
        # Checks if the vector store has been initialized before attempting to query.
        if self.vector_store is None:
            raise RuntimeError("Vector store is empty. Run ingest_documents() first.")

        # Configure the retriever to fetch the top 3 most relevant documents.
        retriever = self.vector_store.as_retriever(search_kwargs={"k": 3})

        # Define the prompt template for the LLM, instructing it to use the provided context.
        prompt = PromptTemplate.from_template("""
You are a helpful assistant. Answer the question using ONLY the context below.
If the answer is not in the context, say "I don't have enough information."

Context:
{context}

Question: {question}

Answer:""")

        # ✅ Modern LCEL chain — replaces create_retrieval_chain entirely.
        # This function formats the retrieved documents into a single string.
        def format_docs(docs):
            return "\n\n".join(doc.page_content for doc in docs)

        # Construct the RAG chain using LangChain Expression Language (LCEL).
        # 1. Retrieve documents based on the question.
        # 2. Format the retrieved documents.
        # 3. Combine with the question into the prompt.
        # 4. Pass the prompt to the LLM.
        # 5. Parse the LLM's output.
        chain = (
            {"context": retriever | format_docs, "question": RunnablePassthrough()}
            | prompt
            | self.llm
            | StrOutputParser()
        )

        print(f"\n🔍 Question: {question}")
        # Invoke the RAG chain with the user's question.
        answer = chain.invoke(question)
        return answer


# --- Run ---
# Instantiate the RAGSystem class.
rag = RAGSystem()

# If no vector store is found, ingest documents to build one.
if rag.vector_store is None:
    rag.ingest_documents()

# Example query to the RAG system.
answer = rag.query("What are the main skills or objectives mentioned in the resume?")
print("\n📝 Answer:\n", answer)